// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit.
import { handle as h0 } from "../endpoints/admin/audit_logs_GET";
import { handle as h1 } from "../endpoints/admin/confirm_payment_POST";
import { handle as h2 } from "../endpoints/admin/decide_dispute_POST";
import { handle as h3 } from "../endpoints/admin/review_submission_POST";
import { handle as h4 } from "../endpoints/admin/update_user_POST";
import { handle as h5 } from "../endpoints/admin/users_GET";
import { handle as h6 } from "../endpoints/auth/login_with_password_POST";
import { handle as h7 } from "../endpoints/auth/logout_POST";
import { handle as h8 } from "../endpoints/auth/register_with_password_POST";
import { handle as h9 } from "../endpoints/auth/session_GET";
import { handle as h10 } from "../endpoints/campaigns/detail_GET";
import { handle as h11 } from "../endpoints/campaigns/list_GET";
import { handle as h12 } from "../endpoints/campaigns/participation_POST";
import { handle as h13 } from "../endpoints/campaigns/save_POST";
import { handle as h14 } from "../endpoints/campaigns/status_POST";
import { handle as h15 } from "../endpoints/claims/create_POST";
import { handle as h16 } from "../endpoints/claims/list_GET";
import { handle as h17 } from "../endpoints/dashboard/summary_GET";
import { handle as h18 } from "../endpoints/disputes/create_POST";
import { handle as h19 } from "../endpoints/disputes/list_GET";
import { handle as h20 } from "../endpoints/profile/me_GET";
import { handle as h21 } from "../endpoints/profile/update_POST";
import { handle as h22 } from "../endpoints/submissions/detail_GET";
import { handle as h23 } from "../endpoints/submissions/list_GET";
import { handle as h24 } from "../endpoints/submissions/save_POST";
import { handle as h25 } from "../endpoints/uploads/presign_POST";

export type Handler = (request: Request) => Promise<Response> | Response;

export const routes: Record<string, Handler> = {
  "admin/audit_logs:GET": h0,
  "admin/confirm_payment:POST": h1,
  "admin/decide_dispute:POST": h2,
  "admin/review_submission:POST": h3,
  "admin/update_user:POST": h4,
  "admin/users:GET": h5,
  "auth/login_with_password:POST": h6,
  "auth/logout:POST": h7,
  "auth/register_with_password:POST": h8,
  "auth/session:GET": h9,
  "campaigns/detail:GET": h10,
  "campaigns/list:GET": h11,
  "campaigns/participation:POST": h12,
  "campaigns/save:POST": h13,
  "campaigns/status:POST": h14,
  "claims/create:POST": h15,
  "claims/list:GET": h16,
  "dashboard/summary:GET": h17,
  "disputes/create:POST": h18,
  "disputes/list:GET": h19,
  "profile/me:GET": h20,
  "profile/update:POST": h21,
  "submissions/detail:GET": h22,
  "submissions/list:GET": h23,
  "submissions/save:POST": h24,
  "uploads/presign:POST": h25,
};
