/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiResult = "fail" | "need_review" | "pass";

export type CampaignPlatform = "any" | "facebook" | "instagram" | "tiktok" | "x" | "youtube";

export type CampaignStatus = "active" | "completed" | "draft" | "expired";

export type ClaimStatus = "paid" | "pending" | "rejected";

export type DisputeStatus = "accepted" | "pending" | "rejected";

export type DuplicatePolicy = "fail" | "need_review";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ParticipantStatus = "active" | "stopped";

export type SocialPlatform = "facebook" | "instagram" | "tiktok" | "x" | "youtube";

export type SubmissionStatus = "admin_approved" | "admin_rejected" | "ai_failed" | "ai_passed" | "ai_verifying" | "claimable" | "claimed" | "disputed" | "draft" | "need_admin_review" | "paid" | "submitted";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "creator" | "owner";

export interface AuditLogs {
  action: string;
  actorId: number | null;
  actorRole: string | null;
  createdAt: Generated<Timestamp>;
  detail: Json | null;
  entityId: number;
  entityType: string;
  fromStatus: string | null;
  id: Generated<number>;
  toStatus: string | null;
}

export interface CampaignParticipants {
  campaignId: number;
  creatorId: number;
  id: Generated<number>;
  joinedAt: Generated<Timestamp>;
  status: Generated<ParticipantStatus>;
  stoppedAt: Timestamp | null;
}

export interface Campaigns {
  budgetReserved: Generated<Int8>;
  budgetTotal: Int8;
  budgetUsed: Generated<Int8>;
  createdAt: Generated<Timestamp>;
  description: string;
  duplicatePolicy: Generated<DuplicatePolicy>;
  editingRequirement: string | null;
  endDate: Timestamp;
  feePerSubmission: Generated<Int8>;
  id: Generated<number>;
  maxPayoutPerSubmission: Generated<Int8>;
  minViews: Generated<number>;
  name: string;
  ownerId: number;
  ratePerThousandViews: Generated<Int8>;
  requiredCaption: string | null;
  requiredHashtags: Generated<string[]>;
  requiredPlatform: Generated<CampaignPlatform>;
  startDate: Timestamp;
  status: Generated<CampaignStatus>;
  target: string;
  targetViews: number | null;
  updatedAt: Generated<Timestamp>;
  watermarkLogoFilename: string | null;
  watermarkLogoUrl: string | null;
  watermarkRequired: Generated<boolean>;
}

export interface Claims {
  adminId: number | null;
  adminNote: string | null;
  amount: Int8;
  bankAccountHolder: string;
  bankAccountNumber: string;
  bankName: string;
  campaignId: number;
  createdAt: Generated<Timestamp>;
  creatorId: number;
  id: Generated<number>;
  paidAt: Timestamp | null;
  paymentReference: string | null;
  phone: string;
  realName: string;
  status: Generated<ClaimStatus>;
  submissionId: number;
}

export interface CreatorSocialAccounts {
  createdAt: Generated<Timestamp>;
  handle: string;
  id: Generated<number>;
  platform: SocialPlatform;
  userId: number;
}

export interface Disputes {
  adminId: number | null;
  adminNote: string | null;
  createdAt: Generated<Timestamp>;
  creatorId: number;
  evidenceFilename: string | null;
  id: Generated<number>;
  reason: string;
  resolvedAt: Timestamp | null;
  status: Generated<DisputeStatus>;
  submissionId: number;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Submissions {
  accountHandle: string;
  adminDecidedAt: Timestamp | null;
  adminId: number | null;
  adminNote: string | null;
  aiChecks: Json | null;
  aiResult: AiResult | null;
  aiSummary: string | null;
  aiVerifiedAt: Timestamp | null;
  approvedAmount: Int8 | null;
  calculatedAmount: Int8 | null;
  campaignId: number;
  caption: Generated<string>;
  contentFingerprint: string;
  contentUrl: string;
  createdAt: Generated<Timestamp>;
  creatorId: number;
  creatorNotes: string | null;
  editingConfirmed: Generated<boolean>;
  hashtags: Generated<string[]>;
  id: Generated<number>;
  platform: SocialPlatform;
  proofScreenshotFilename: string | null;
  sequenceNo: number;
  status: Generated<SubmissionStatus>;
  submittedAt: Timestamp | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  verifiedViews: number | null;
  viewsClaimed: Generated<number>;
  watermarkApplied: Generated<boolean>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  bio: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  auditLogs: AuditLogs;
  campaignParticipants: CampaignParticipants;
  campaigns: Campaigns;
  claims: Claims;
  creatorSocialAccounts: CreatorSocialAccounts;
  disputes: Disputes;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  submissions: Submissions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","creator","owner"];
export const SocialPlatformArrayValues: [SocialPlatform, ...SocialPlatform[]] = ["facebook","instagram","tiktok","x","youtube"];
export const CampaignPlatformArrayValues: [CampaignPlatform, ...CampaignPlatform[]] = ["any","facebook","instagram","tiktok","x","youtube"];
export const CampaignStatusArrayValues: [CampaignStatus, ...CampaignStatus[]] = ["active","completed","draft","expired"];
export const DuplicatePolicyArrayValues: [DuplicatePolicy, ...DuplicatePolicy[]] = ["fail","need_review"];
export const ParticipantStatusArrayValues: [ParticipantStatus, ...ParticipantStatus[]] = ["active","stopped"];
export const SubmissionStatusArrayValues: [SubmissionStatus, ...SubmissionStatus[]] = ["admin_approved","admin_rejected","ai_failed","ai_passed","ai_verifying","claimable","claimed","disputed","draft","need_admin_review","paid","submitted"];
export const AiResultArrayValues: [AiResult, ...AiResult[]] = ["fail","need_review","pass"];
export const DisputeStatusArrayValues: [DisputeStatus, ...DisputeStatus[]] = ["accepted","pending","rejected"];
export const ClaimStatusArrayValues: [ClaimStatus, ...ClaimStatus[]] = ["paid","pending","rejected"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.