// Generates src/routes.generated.tsx from src/pages/*.tsx (Floot/Remix-style flat routes)
// and src/server/routes.ts from src/endpoints/**/<name>_<METHOD>.ts.
import { readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const pagesDir = join(root, "src/pages");
const endpointsDir = join(root, "src/endpoints");

// ---------- pages ----------
const pageFiles = readdirSync(pagesDir).filter(
  (f) => f.endsWith(".tsx") && !f.endsWith(".pageLayout.tsx") && !f.endsWith(".spec.tsx")
);
const layoutFiles = new Set(readdirSync(pagesDir).filter((f) => f.endsWith(".pageLayout.tsx")));

function toPath(name) {
  if (name === "_index") return "/";
  const parts = name.split(".").map((seg) => {
    if (seg === "_index") return "";
    if (seg.startsWith("$")) return ":" + seg.slice(1);
    return seg;
  });
  return "/" + parts.filter(Boolean).join("/");
}

let imports = [`import type { ReactNode, ComponentType } from "react";`];
let entries = [];
pageFiles
  .sort()
  .forEach((file, i) => {
    const name = file.replace(/\.tsx$/, "");
    const path = toPath(name);
    const pageVar = `Page${i}`;
    imports.push(`import ${pageVar} from "./pages/${name}";`);
    let layoutVar = "[]";
    const layoutFile = `${name}.pageLayout.tsx`;
    if (layoutFiles.has(layoutFile)) {
      layoutVar = `Layout${i}`;
      imports.push(`import ${layoutVar} from "./pages/${name}.pageLayout";`);
    }
    entries.push(`  { path: ${JSON.stringify(path)}, element: wrap(${layoutVar}, ${pageVar}) },`);
  });

const routesTsx = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit.
${imports.join("\n")}

type Layout = ComponentType<{ children: ReactNode }>;

function wrap(layouts: Layout[], Page: ComponentType): ReactNode {
  // Layouts are listed outermost-first, e.g. [CreatorRoute, AppShell].
  return layouts.reduceRight<ReactNode>((child, L) => <L>{child}</L>, <Page />);
}

export const routes: Array<{ path: string; element: ReactNode }> = [
${entries.join("\n")}
];
`;
writeFileSync(join(root, "src/routes.generated.tsx"), routesTsx);

// ---------- endpoints ----------
function walk(dir) {
  const out = [];
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (/_(GET|POST)\.ts$/.test(f)) out.push(p);
  }
  return out;
}
const endpointFiles = walk(endpointsDir).sort();
let eImports = [];
let eEntries = [];
endpointFiles.forEach((file, i) => {
  const rel = relative(endpointsDir, file).replace(/\\/g, "/").replace(/\.ts$/, "");
  const m = rel.match(/^(.*)_(GET|POST)$/);
  const route = m[1];
  const method = m[2];
  eImports.push(`import { handle as h${i} } from "../endpoints/${rel}";`);
  eEntries.push(`  ${JSON.stringify(`${route}:${method}`)}: h${i},`);
});
const serverTs = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit.
${eImports.join("\n")}

export type Handler = (request: Request) => Promise<Response> | Response;

export const routes: Record<string, Handler> = {
${eEntries.join("\n")}
};
`;
writeFileSync(join(root, "src/server/routes.ts"), serverTs);
console.log(`routes: ${pageFiles.length} pages, ${endpointFiles.length} endpoints`);
