// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit.
import type { ReactNode, ComponentType } from "react";
import Page0 from "./pages/_index";
import Layout0 from "./pages/_index.pageLayout";
import Page1 from "./pages/admin.ai-review";
import Layout1 from "./pages/admin.ai-review.pageLayout";
import Page2 from "./pages/admin.audit-log";
import Layout2 from "./pages/admin.audit-log.pageLayout";
import Page3 from "./pages/admin.campaigns.$campaignId";
import Layout3 from "./pages/admin.campaigns.$campaignId.pageLayout";
import Page4 from "./pages/admin.campaigns";
import Layout4 from "./pages/admin.campaigns.pageLayout";
import Page5 from "./pages/admin.claims";
import Layout5 from "./pages/admin.claims.pageLayout";
import Page6 from "./pages/admin.dashboard";
import Layout6 from "./pages/admin.dashboard.pageLayout";
import Page7 from "./pages/admin.disputes";
import Layout7 from "./pages/admin.disputes.pageLayout";
import Page8 from "./pages/admin.payments";
import Layout8 from "./pages/admin.payments.pageLayout";
import Page9 from "./pages/admin.submissions.$submissionId";
import Layout9 from "./pages/admin.submissions.$submissionId.pageLayout";
import Page10 from "./pages/admin.submissions";
import Layout10 from "./pages/admin.submissions.pageLayout";
import Page11 from "./pages/admin.users";
import Layout11 from "./pages/admin.users.pageLayout";
import Page12 from "./pages/creator.campaigns.$campaignId";
import Layout12 from "./pages/creator.campaigns.$campaignId.pageLayout";
import Page13 from "./pages/creator.campaigns";
import Layout13 from "./pages/creator.campaigns.pageLayout";
import Page14 from "./pages/creator.dashboard";
import Layout14 from "./pages/creator.dashboard.pageLayout";
import Page15 from "./pages/creator.my-campaigns";
import Layout15 from "./pages/creator.my-campaigns.pageLayout";
import Page16 from "./pages/creator.payments";
import Layout16 from "./pages/creator.payments.pageLayout";
import Page17 from "./pages/creator.profile";
import Layout17 from "./pages/creator.profile.pageLayout";
import Page18 from "./pages/creator.submissions.$submissionId.claim";
import Layout18 from "./pages/creator.submissions.$submissionId.claim.pageLayout";
import Page19 from "./pages/creator.submissions.$submissionId.dispute";
import Layout19 from "./pages/creator.submissions.$submissionId.dispute.pageLayout";
import Page20 from "./pages/creator.submissions.$submissionId";
import Layout20 from "./pages/creator.submissions.$submissionId.pageLayout";
import Page21 from "./pages/creator.submissions";
import Layout21 from "./pages/creator.submissions.pageLayout";
import Page22 from "./pages/creator.submit";
import Layout22 from "./pages/creator.submit.pageLayout";
import Page23 from "./pages/login";
import Layout23 from "./pages/login.pageLayout";
import Page24 from "./pages/owner.budget";
import Layout24 from "./pages/owner.budget.pageLayout";
import Page25 from "./pages/owner.campaigns.$campaignId.edit";
import Layout25 from "./pages/owner.campaigns.$campaignId.edit.pageLayout";
import Page26 from "./pages/owner.campaigns.$campaignId";
import Layout26 from "./pages/owner.campaigns.$campaignId.pageLayout";
import Page27 from "./pages/owner.campaigns.new";
import Layout27 from "./pages/owner.campaigns.new.pageLayout";
import Page28 from "./pages/owner.campaigns";
import Layout28 from "./pages/owner.campaigns.pageLayout";
import Page29 from "./pages/owner.dashboard";
import Layout29 from "./pages/owner.dashboard.pageLayout";
import Page30 from "./pages/owner.payments";
import Layout30 from "./pages/owner.payments.pageLayout";
import Page31 from "./pages/owner.submissions.$submissionId";
import Layout31 from "./pages/owner.submissions.$submissionId.pageLayout";
import Page32 from "./pages/owner.submissions";
import Layout32 from "./pages/owner.submissions.pageLayout";
import Page33 from "./pages/register";
import Layout33 from "./pages/register.pageLayout";

type Layout = ComponentType<{ children: ReactNode }>;

function wrap(layouts: Layout[], Page: ComponentType): ReactNode {
  // Layouts are listed outermost-first, e.g. [CreatorRoute, AppShell].
  return layouts.reduceRight<ReactNode>((child, L) => <L>{child}</L>, <Page />);
}

export const routes: Array<{ path: string; element: ReactNode }> = [
  { path: "/", element: wrap(Layout0, Page0) },
  { path: "/admin/ai-review", element: wrap(Layout1, Page1) },
  { path: "/admin/audit-log", element: wrap(Layout2, Page2) },
  { path: "/admin/campaigns/:campaignId", element: wrap(Layout3, Page3) },
  { path: "/admin/campaigns", element: wrap(Layout4, Page4) },
  { path: "/admin/claims", element: wrap(Layout5, Page5) },
  { path: "/admin/dashboard", element: wrap(Layout6, Page6) },
  { path: "/admin/disputes", element: wrap(Layout7, Page7) },
  { path: "/admin/payments", element: wrap(Layout8, Page8) },
  { path: "/admin/submissions/:submissionId", element: wrap(Layout9, Page9) },
  { path: "/admin/submissions", element: wrap(Layout10, Page10) },
  { path: "/admin/users", element: wrap(Layout11, Page11) },
  { path: "/creator/campaigns/:campaignId", element: wrap(Layout12, Page12) },
  { path: "/creator/campaigns", element: wrap(Layout13, Page13) },
  { path: "/creator/dashboard", element: wrap(Layout14, Page14) },
  { path: "/creator/my-campaigns", element: wrap(Layout15, Page15) },
  { path: "/creator/payments", element: wrap(Layout16, Page16) },
  { path: "/creator/profile", element: wrap(Layout17, Page17) },
  { path: "/creator/submissions/:submissionId/claim", element: wrap(Layout18, Page18) },
  { path: "/creator/submissions/:submissionId/dispute", element: wrap(Layout19, Page19) },
  { path: "/creator/submissions/:submissionId", element: wrap(Layout20, Page20) },
  { path: "/creator/submissions", element: wrap(Layout21, Page21) },
  { path: "/creator/submit", element: wrap(Layout22, Page22) },
  { path: "/login", element: wrap(Layout23, Page23) },
  { path: "/owner/budget", element: wrap(Layout24, Page24) },
  { path: "/owner/campaigns/:campaignId/edit", element: wrap(Layout25, Page25) },
  { path: "/owner/campaigns/:campaignId", element: wrap(Layout26, Page26) },
  { path: "/owner/campaigns/new", element: wrap(Layout27, Page27) },
  { path: "/owner/campaigns", element: wrap(Layout28, Page28) },
  { path: "/owner/dashboard", element: wrap(Layout29, Page29) },
  { path: "/owner/payments", element: wrap(Layout30, Page30) },
  { path: "/owner/submissions/:submissionId", element: wrap(Layout31, Page31) },
  { path: "/owner/submissions", element: wrap(Layout32, Page32) },
  { path: "/register", element: wrap(Layout33, Page33) },
];
